#!/bin/bash

#FileChecker

filename=$1

FileNamePlaceholder=*REDACTED*

if [ -f "$filename" ]; then
echo "Filen du sjekker etter finnes på systemet, et eller annet sted!"
else
echo "Filen har forsvunnet i skyen"
fi
